### PR TITLE
python2 compatibilty fix by Mika Eloranta

### PR DESCRIPTION
**Pull request by paulwouters**

### CODE REVIEW

**Comment by martindurant** [comment]
Do we support py2? I don't see any wheels, and conda-forge no longer builds for py2. None of the tests above run on py2.

**Comment by paulwouters** [comment]
Well, it seems that is what the ubuntu 20.x is running in the failing test case ? I just wanted to see if this would fix it but it did not.

**Comment by paulwouters** [comment]
Either python2 support should be fixed, or the CI/CD should remove the python2 cases (eg on the ubuntu 20.04 test case)

**Comment by martindurant** [comment]
OK, running this now - and we can consider dropping py2 in a separate issue/PR. Sorry for the wait!

**Comment by martindurant** [comment]
Does *not* seem to resolve failures

**Pull request closed without merging**
